### ISSUE TITLE
ESI Render Issue

### ISSUE THREAD

**Issue by andrew-ebsco** [fastly/fastly-magento#34]
On our Magento site, we are showing the product_compare sidebar on every page as part of a dropdown. With the Fastly extension enabled, that block is being converted to an <esi:include>. However, on the sales/order/view page in the customer account, the esi:include is returning a 503 error. I figured out the issue is that on the order view, the esi:include src included `sales_order_view` in the `layout_handles` GET parameter, causing Magento to try to render that block and throwing an error. As a fix, I added `sales` to the `$skipHandles` array on the `_getLayoutHandles` method of the `Fastly_CDN_Model_Esi_Tag_Abstract` class. 

That fixed the problem for now, but are there any potential consequences of skipping the `sales` layout handles? Is there a better way to handle esi:include errors?

Thanks for your help!

**Comment by vvuksan** [comment]
I didn't see the notification before but we'll take a look.

**Comment by vvuksan** [comment]
This has been addressed in #37. This will go out with the 1.0.18 release of the plugin.
