### ISSUE TITLE
Remove magento admin pages from the cache

### ISSUE THREAD

**Issue by viv81ster** [fastly/fastly-magento#39]
Hi

I faced with a problem when after saving of system configuration nothing happens.
You get a system success message only if you go to some another page.
And you can see you changed system config data only after flushing of fastly CDN cache.

Is it possible that the admin pages are falling into fastly CDN?

Thanks!

**Comment by vvuksan** [comment]
That doesn't sound like the behavior you should be seeing. Can you please open up a support request with our support team

https://fastly.zendesk.com/hc/en-us/articles/204950779-Filing-support-tickets
